### ISSUE TITLE
maildir vs mbox

### ISSUE THREAD

**Issue by rpgd60** [devmount/thunderbird-stats#12]
**Is your feature request related to a problem? Please describe.**
I would love to use this utility, but thunderbird-stats supports only Maildir storage -  mbox is the default mail storage method, also  recommended by Thunderbird (see [docs](http://mzl.la/1GDeRsp))

**Describe the solution you'd like**
generate stats  for the Thunderbird default mbox mail storage system

**Describe alternatives you've considered**
Move to Maildir.  I have some 30G of email.   
Unfortunately,  Maildir storage is discouraged by Thunderbird itself in the Maildir documentation (quote from link above): *"We suggest you leave Maildir disabled unless you are an advanced user, willing to risk your data, and know how to back up your email before turning on Maildir and how to restore it if you run into problems."*

**Additional context**
Another [link (2017)](https://wiki.mozilla.org/Thunderbird/Maildir) to Maildir documentation: 
I realize that this request may not be trivial, but I think it is useful to document further the requirement to use Maildir.

Thank you for this utility

**Comment by devmount** [comment]
Thank you for this request and your interest in this tool. Let me first assure you, that it was not an easy decision for `maildir` and against `mbox`. The main reason was, that extracting information from `mbox` files is a mess, also due to lack of proper documentation. With `maildir`, you have one file for each email containing meta data and email content. So that was much easier to process and evaluate.

If you can show me a way to iterate over all emails of an `mbox` file and extract the following information:

- timestamp when email was sent
- timestamp when email was received
- email address, email was sent from
- status (read or unread)

I'm willing to implement this tool for `mbox` accounts too.

**Comment by devmount** [comment]
Also FYI (`maildir` is on it's way to become the default mail storage format):
![image](https://user-images.githubusercontent.com/5441654/93079249-1c5e0700-f68c-11ea-8673-34aad3f0de66.png)

See https://developer.thunderbird.net/planning/roadmap#maildir-tb-78

**Comment by rpgd60** [comment]
Thank you for your reply.

> If you can show me a way to iterate over all emails of an `mbox` file and extract the following information:

I'm afraid I cannot show you that.  My professional and personal  interests do not include the innards of mail systems.

**Comment by rpgd60** [comment]
> Also FYI (`maildir` is on it's way to become the default mail storage format):

Thanks for the info.   I suppose that is good news, but looking at the link provided it does not look like it will happen any time soon.
The day full maildir support shows up in the release notes and they remove the stern warning I may give it a try.   

In the meantime, I would take the liberty to suggest that you provide in the README a bit more info on the present status of maildir.

**Comment by devmount** [comment]
> I'm afraid I cannot show you that. My professional and personal interests do not include the innards of mail systems.

No problem, I didn't expected that 😅 I'm currently evaluating a way to implement this tool as a Thunderbird 78+ add-on. I'll let you know, when I have any update on this.

> The day full maildir support shows up in the release notes and they remove the stern warning I may give it a try.

Sure.

> In the meantime, I would take the liberty to suggest that you provide in the README a bit more info on the present status of maildir.

Thank you for this suggestion. I will add a corresponding comment to the readme 👍🏻

**Comment by devmount** [comment]
@rpgd60 I ported this tool into a thunderbird add-on, where your storage format doesn't matter. It's currently in beta, maybe you can have a look at it and test it a bit? I will soon upload it to the Thunderbird add-on repository, but you can already install it by file
https://github.com/devmount/third-stats/releases/download/v0.2.5/thirdstats_v0.2.5.zip

Let me know, if this helps you.

**Comment by rpgd60** [comment]
Hi Andreas

Many thanks. I will test it this weekend and vive u feedback.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by devmount** [comment]
Hi Rafael,

ThirdStats v0.3.3 is now released as [an official Thunderbird add-on](https://addons.thunderbird.net/en-US/thunderbird/addon/thirdstats). You can install and test it from there. Please open [an issue on the ThirdStats repo](https://github.com/devmount/third-stats/issues/new?template=bug_report.md) if you run into any problems. Thank you.
