### ISSUE TITLE
Separate stats for every email address

### ISSUE THREAD

**Issue by thefatcode** [devmount/thunderbird-stats#2]
I was trying to modify this one to have separate stats in every e-mail addresses added in the configuration file but I cannot make it work as to what I wanted it to. Im still learning vue and python and web development in general.

Right now, I really really like it to have a separate stats for every e-mail addresses that I have added in the configuration file.

This project is really really useful and very beautiful.

**Comment by devmount** [comment]
@thefatcode Do you mean separate stats for every email *account* in Thunderbird (configured as `ThunderbirdProfilePath` in config.ini) or every email *address* (configured as `EmailAddresses` in config.ini)?

**Comment by thefatcode** [comment]
@devmount Hi, In every email addresses that I added in the EmailAddresses will have its own statistics displayed is what I meant. Thank you Andreas!

**Comment by devmount** [comment]
I implemented this. 

![thunderbird_address_switch](https://user-images.githubusercontent.com/5441654/76033977-e18d5080-5f3d-11ea-8919-2eaa3982a752.png)

Please test with the current version.

**Comment by thefatcode** [comment]
This is my config.ini,
![Screenshot_11](https://user-images.githubusercontent.com/50254310/76035774-3f8d5880-5f7d-11ea-9b38-85f9559b5e56.png)

This is the total,
![Screenshot_10](https://user-images.githubusercontent.com/50254310/76035682-00f79e00-5f7d-11ea-9687-55b6b4f3a451.png)

This is my first e-mail,
![Screenshot_12](https://user-images.githubusercontent.com/50254310/76035825-68155280-5f7d-11ea-8871-a4e12f5874bb.png)

This is my other e-mail,
![Screenshot_13](https://user-images.githubusercontent.com/50254310/76035882-909d4c80-5f7d-11ea-8355-ce39dbd882e2.png)

**Comment by thefatcode** [comment]
Hi Andreas, thank you and I understand. Will each of the e-mail's unread stats be fixed eventually?

**Comment by devmount** [comment]
Unfortunately, Thunderbird stores the unread information in separate files in a way that is impossible to easily match the corresponding email address, sorry. Maybe somebody knows another way to get these information?

**Comment by thefatcode** [comment]
Hi,

That is very unfortunate to hear Andreas. But your tool works and is best as is already so thank you so much!

**Comment by devmount** [comment]
You're very welcome and thank you for your feedback and ideas! When I find a way, I'll reopen this thread.
