### ISSUE TITLE
Unread Email Stats

### ISSUE THREAD

**Issue by devmount** [devmount/thunderbird-stats#3]
In addition to the current general mail count, it would be nice to also have the number of unread mails.

**Comment by devmount** [comment]
Implemented with 150c1d0b35d99fbc7efa71ae8ca671b64118899a

![tes_unread](https://user-images.githubusercontent.com/5441654/75825493-c5ef4200-5da5-11ea-8429-37d046c1034b.png)

@thefatcode Can you test, if the unread count is correct on your machine?

**Comment by thefatcode** [comment]
Hi there! I have tried it with 2 email accounts in my thunderbird with 3 un-reads in all but it displays 0 in the web page. Thank you Andreas.

**Comment by thefatcode** [comment]
Hi there again Andreas, So I tried removing the accounts and cleaned up the ImapMail folder (I am using windows btw) and re-added the account, at first when I scan for the stats the un-read was not being read, so what I did was I go to the thunderbird and clicked on a mail that was not being read yet and go back to scan for the mails via 'python stats.py' and then the un-read was now being read.

**Comment by devmount** [comment]
Thanks for testing. I fixed a small bug on unread mail calculation (65fe1baa4c3b5bc01a2a3cb4ae64b9ff1e56fe06) - can you please test again, if the problem's still there?

**Comment by thefatcode** [comment]
Hi Andreas, the calculation looks good now. However, it seems that if I add another e-mail address in the config file in which I have added in the thunderbird too.. the first email is the only e-mail that will read the sent mails and will leave the un-read number to stay even if I have removed the email that has un-read mails. Or is this normal because you are going to make them separate? Thank you Andreas!

**Comment by devmount** [comment]
This tool currently only supports **one** email account in Thunderbird (which is configured via the corresponding directory you set in `config.ini`>`ThunderbirdProfilePath` - i just realized that this is a bit misleading... actually this should be called `ThunderbirdAccountPath`... 😅). The list of email addresses is necessary to distinguish between received and sent mails in this account...

So yes, if you use more than one account at the moment, there will be unexpected behaviour 😇

**Comment by thefatcode** [comment]
Thank you so much for clearing that up for me Andreas! ☺️
