### ISSUE TITLE
Account Path Variable

### ISSUE THREAD

**Issue by thefatcode** [devmount/thunderbird-stats#4]
**Describe the bug**
Processing the mails via 'python stats.py' gives error reading the ThunderbirdProfilePath. 

**To Reproduce**
1. Go to the thunderbird-stats directory
2. Open a terminal.
3. Type in 'python stats.py' without the single quotes.

**Expected behavior**
It should process the mails being scanned and does show how many is currently being scanned over the total mails it is going to scan.

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Browser: Google Chrome
 - Version: 80.0.3987.132

**Comment by devmount** [comment]
Which Python version do you use? What exactly is the error message?

**Comment by thefatcode** [comment]
Hi Andreas,, the fix would only to rename the ThunderbirdProfilePath variable in the config.ini to ThunderbirdAccountPath.

**Comment by devmount** [comment]
My fault, totally forgot to rename it in the default config file. Thank you!
