### ISSUE TITLE
Add total un-read instead of separating.

### ISSUE THREAD

**Issue by thefatcode** [devmount/thunderbird-stats#6]
**Is your feature request related to a problem? Please describe.**
Since it is impossible to have un-read stats in each e-mails. Could it be possible to just add all un-read mails in all e-mails added or in the ThunderbirdProfile/AccountPath? 

**Describe the solution you'd like**
The solution I would like is to add all those un-read mails and then display it, same as usual.

**Describe alternatives you've considered**
No alternatives in my mind at the moment.

**Additional context**
None at the moment.

Thank you Andreas!

**Comment by devmount** [comment]
Sorry, I don't quite get what you're trying to do. What do you mean by "just add all un-read mails"? Do you want to manually put the unread number for each address into the config.ini? Or do you just want to show the total un-read number, doesn't matter what was selected in the email select field?

**Comment by thefatcode** [comment]
Hi Andreas, 

Since it is almost impossible to have each e-mail's un-read count, what I would like it to have is to maybe just display the over all un-read mails in the whole "ImapMail" folder no matter what e-mail it is for. Thank you so much!

**Comment by thefatcode** [comment]
Hi there again Andreas,

We are very sorry for annoying you throughout the request that we wanted. We have read an article about the mail dir in the official thunderbird support page which is this:
![image](https://user-images.githubusercontent.com/50254310/76215992-c9257a80-624a-11ea-96c2-f3546cbf78d0.png)
We would like to thank you for trying your best just to get what we want. Still hoping for the consideration of making this tool just add all un-read mails and display it. Thank you once again Andreas!

**Comment by devmount** [comment]
The article you mentioned is underlining exactly what I was trying to explain. Message flags are currently not stored with emails. So I cannot determine the number of unread emails each email account has.

And as [I wrote earlier](https://github.com/devmount/thunderbird-stats/issues/3#issuecomment-594508920), this tool currently only supports **one** imap account. When I have the time, I will add support for multiple email accounts.

**Comment by thefatcode** [comment]
Hi there Andreas!

Thank you for your response once again. What I do now is make another folder in the web host per account and set the config to the corresponding e-mail and it works. Now we have different browser window per e-mail account to see the stats.

**Comment by devmount** [comment]
Nice workaround!
