### ISSUE TITLE
KeyError: 'newest' 

### ISSUE THREAD

**Issue by fabrizioschiano** [devmount/thunderbird-stats#8]
**Describe the bug**
I run ./stats.py and I receive the following error

```
Processing mails...
0mails [00:00, ?mails/s]
Traceback (most recent call last):
  File "./stats.py", line 201, in <module>
    if stats():
  File "./stats.py", line 172, in stats
    meta['total']['days'] = (time.mktime(meta['total']['newest']) - time.mktime(meta['total']['oldest']))/(60*60*24)
KeyError: 'newest'
```

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: not relevant
 - Version: not relevant

**Comment by devmount** [comment]
Did you run the stats.py after a fresh install for the first time or does this occure after you already used this tool for some time?

**Comment by fabrizioschiano** [comment]
It is the first time I use it.

**Comment by devmount** [comment]
How does your `ThunderbirdAccountPath` in the `config.ini` look like? Check if you have set it correctly.

When using this tool on Bash under Windows (WSL), the path looks like this:
`/mnt/c/Users/<username>/AppData/Roaming/Thunderbird/Profiles/<abcdefgh>.default-release/ImapMail/<mail.your-server.de>` (mind the placeholders)

**Comment by fabrizioschiano** [comment]
This is how it looks like:
```
ThunderbirdAccountPath = /home/schiano/.thunderbird/s4oa7khy.default-release/ImapMail/ewa.epfl.ch
EmailAddresses = fabrizio.schiano@epfl.ch
```

**Comment by devmount** [comment]
I updated the `stats.py`. Can you please git pull the changes, try again and paste the script output? I assume there is something wrong with your path...

**Comment by devmount** [comment]
@fabrizioschiano Any update on this?
